name: AVDBS t22 Bot (v6.1)
on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Run bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          AVDBS_COOKIE: ${{ secrets.AVDBS_COOKIE }}
        run: python -u main.py

- name: Commit state if changed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name  "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add state/ || true
            git commit -m "chore(state): update seen_ids [skip ci]" || true
            git pull --rebase || true
            git push || true
          else
            echo "No state changes."
          fi